server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    instance:
      hostname: localhost